def pfa(n):
    print("The factors of the users number(stored in a py file) are listed below(generated by the good old 'for i in range' loop) :")
    for i in range(1, n+1):
        if n % i == 0:
            print(i)

number = int(input("Enter users nmber here, then it will be taken into a custom function called pfa and then it will have a for loop on it and the factors will be listed line by line: "))
pfa(number)